/** Deterministic helpers for demo generators (same input → same output). */

export function hashString(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function seededRandom(seed: string): () => number {
  let a = hashString(seed) || 1;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function pick<T>(rand: () => number, items: readonly T[]): T {
  return items[Math.floor(rand() * items.length) % items.length]!;
}

export function scoreBetween(rand: () => number, lo: number, hi: number): number {
  return Math.round((lo + rand() * (hi - lo)) * 10) / 10;
}

export function titleCase(s: string): string {
  return s
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => (w.length <= 3 && w === w.toUpperCase() ? w : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()))
    .join(" ");
}

export const DEMO_LABEL = "DEMO OUTPUT — generated by the deterministic demo provider without AI or live research. Replace with a real run before relying on it.";

/** Pulls the subject out of a mission prompt ("Research 15 HVAC-related niches" → "HVAC-related"). */
export function missionSubject(prompt: string): string {
  let s = prompt.trim().replace(/[.!?]+$/, "");
  s = s.replace(/^(please\s+)?(research|find|discover|investigate|scout|explore|identify)\s+/i, "");
  s = s.replace(/^(whether|if)\s+/i, "");
  s = s.replace(/^\d+\s+|^(one|two|three|four|five|six|seven|eight|nine|ten|twelve|fifteen|twenty|thirty)\s+/i, "");
  s = s.replace(/\b(is|are)\s+(a|an)?\s*(strong|good|viable|promising)?\s*(pod|print[- ]on[- ]demand)?\s*(market|niche|opportunit(y|ies))\b.*$/i, "");
  s = s.replace(/\b(emerging|underserved|promising|new)\b\s*/gi, "");
  s = s.replace(/\b(pod|print[- ]on[- ]demand)\s*/gi, "");
  s = s.replace(/\b(niches?|markets?|opportunit(y|ies)|professions?)\b(\s+with\s+.*)?$/i, "");
  s = s.replace(/\s+/g, " ").trim();
  return s.length >= 2 ? s : prompt.trim().slice(0, 60);
}

export function isAiSiSubject(text: string): boolean {
  return /superintelligen|\bagi\b|\basi\b|artificial (general |super)?intelligence|\bai\b|singularity|alignment/i.test(text);
}
