import type { Metadata } from "next";
import Link from "next/link";
import { DemoBadge, StatusChip } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/misc";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TBody, TD, TH, THead, TR } from "@/components/ui/table";
import { Time } from "@/components/ui/time";
import { getContext } from "@/server/context";

export const metadata: Metadata = { title: "Stores" };

export default async function StoresPage() {
  const ctx = await getContext();
  const stores = await ctx.db.from("stores").select("id, code, name, status, provider, version, updated_at, is_demo, brands(id, code), store_products(count)").eq("workspace_id", ctx.workspace.id).order("updated_at", { ascending: false });
  return (
    <>
      <PageHeader title="Stores" description="Store packages generated by the Store Builder. Preview them inside POD Lab, export them, and launch only after approval." />
      {stores.data?.length ? (
        <Card>
          <Table>
            <THead>
              <tr>
                <TH>Store</TH>
                <TH>Brand</TH>
                <TH>Status</TH>
                <TH>Target</TH>
                <TH className="text-right">Products</TH>
                <TH>Version</TH>
                <TH>Updated</TH>
                <TH>
                  <span className="sr-only">Actions</span>
                </TH>
              </tr>
            </THead>
            <TBody>
              {stores.data.map((s) => (
                <TR key={s.id}>
                  <TD>
                    <Link href={`/stores/${s.id}`} className="text-ink hover:text-accent">
                      <span className="font-mono text-xs text-muted">{s.code}</span> {s.name}
                    </Link>{" "}
                    <DemoBadge show={s.is_demo} />
                  </TD>
                  <TD className="font-mono text-xs">{s.brands ? <Link href={`/brands/${s.brands.id}`} className="text-accent">{s.brands.code}</Link> : "—"}</TD>
                  <TD>
                    <StatusChip status={s.status} />
                  </TD>
                  <TD className="text-xs">{s.provider.replace(/_/g, " ")}</TD>
                  <TD className="text-right text-xs tabular">{(s.store_products as unknown as Array<{ count: number }>)[0]?.count ?? 0}</TD>
                  <TD className="text-xs">v{s.version}</TD>
                  <TD className="text-xs">
                    <Time value={s.updated_at} />
                  </TD>
                  <TD>
                    <ButtonLink href={`/stores/${s.id}/preview`} size="sm">
                      Preview
                    </ButtonLink>
                  </TD>
                </TR>
              ))}
            </TBody>
          </Table>
        </Card>
      ) : (
        <EmptyState title="No stores yet" description="Approve a brand's product assortment, then run the Store Builder from the brand page." />
      )}
    </>
  );
}
